Add GitHub Actions workflows for hybrid npm/Maven/NuGet publishing (#1099)
## Problem
Relied on Github Actions to do the version increment, but actually any
commits going into main but be done via PR, or have the appropriate
permissions
```
remote: error: GH013: Repository rule violations found for refs/heads/main.        
remote: Review all repository rules at https://github.com/aws/aws-toolkit-common/rules?ref=refs%2Fheads%2Fmain        
remote: 
remote: - Changes must be made through a pull request.        
remote: 
remote: - 4 of 4 required status checks are expected.        
remote: 
To https://github.com/aws/aws-toolkit-common
 ! [remote rejected] main -> main (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/aws/aws-toolkit-common'
Error: Process completed with exit code 1.

```


## Solution
Codepipelines has permission as it authenticates as
`aws-toolkit-automation` user with write permissions to be able to push
commits directly into `main`

### New Flow
1. When user merges PR to main, triggers Github Actions workflow which
immediately triggers the CodePipeline
2. CodePipeline goes through stages 
    1. clone repo
    2. aws-toolkit-automation commits version increment to main
    3. build maven/nuget
    4. publish maven/nuget
3. When aws-toolkit-automation commits version increment to main, Github
Actions workflow will publish npm

<!---
    REMINDER:
    - Read CONTRIBUTING.md first.
    - Add test coverage for your changes.
    - Link to related issues/commits.
    - Testing: how did you test your changes?
    - Screenshots if applicable
-->

## License

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.